### ISSUE TITLE
User able to change difficulty

### ISSUE THREAD

**Issue by hungle546** [hungle546/super-mario-run#3]
The user can change the difficulty of the level. There will be three buttons that the user can choose from which will change how fast the character will be moving making it harder. 
- This can be done by creating three buttons easy, normal, hard
- If the user press easy, medium, hard -> speed of which screen moves will change
- creating the effect that the character is moving faster
- The button will stay a different color to let users know what difficulty setting they are on.

**Comment by onzfonz** [comment]
Make those rates something that can be edited in a text file and you can go with this one
